# Generated by Django 5.0.6 on 2026-09-16 19:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Sequência própria (não reaproveita pipeline_event_seq): dá a ordem
        # total do log de replicação, usada como cursor por peer — ver
        # apps/artifacts/signals_replicacao.py e apps/cluster/replicacao.py.
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS cluster_evento_replicacao_seq AS bigint START WITH 1 INCREMENT BY 1;",
            reverse_sql="DROP SEQUENCE IF EXISTS cluster_evento_replicacao_seq;",
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('apelido', models.CharField(max_length=120)),
                ('hostname_declarado', models.CharField(blank=True, max_length=120)),
                ('modo', models.CharField(choices=[('compute', 'Nó de processamento (banco compartilhado)'), ('replica', 'Réplica (stack própria, sincroniza por eventos)')], max_length=20)),
                ('token_hash', models.CharField(max_length=128)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_rotacao_token_em', models.DateTimeField(blank=True, null=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquinas', to=settings.AUTH_USER_MODEL)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='accounts.organization')),
            ],
            options={
                'db_table': 'cluster_maquina',
            },
        ),
        migrations.CreateModel(
            name='MaquinaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('cpu_count', models.IntegerField(blank=True, null=True)),
                ('ram_total_mb', models.IntegerField(blank=True, null=True)),
                ('ram_disponivel_mb', models.IntegerField(blank=True, null=True)),
                ('disco_disponivel_gb', models.FloatField(blank=True, null=True)),
                ('filas', models.JSONField(blank=True, default=list)),
                ('ultimo_heartbeat_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_evento_sequence', models.BigIntegerField(default=0)),
                ('maquina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='cluster.maquina')),
            ],
            options={
                'db_table': 'cluster_maquina_status',
            },
        ),
        migrations.CreateModel(
            name='EventoReplicacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.BigIntegerField(editable=False, unique=True)),
                ('tipo', models.CharField(max_length=60)),
                ('objeto_id', models.UUIDField()),
                ('payload', models.JSONField()),
                ('ocorrido_em', models.DateTimeField()),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_replicacao', to='accounts.organization')),
                ('origem_maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_emitidos', to='cluster.maquina')),
            ],
            options={
                'db_table': 'cluster_evento_replicacao',
                'indexes': [models.Index(fields=['-sequence'], name='cluster_eve_sequenc_8eeecc_idx'), models.Index(fields=['organizacao', '-sequence'], name='cluster_eve_organiz_3999ec_idx')],
            },
        ),
    ]
