# Generated by Django 5.0.6 on 2026-09-16 22:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='ollama_endpoint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='MaquinaModeloOllama',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_modelo', models.CharField(max_length=200)),
                ('tokens_por_segundo_medio', models.FloatField(blank=True, null=True)),
                ('amostras_n', models.IntegerField(default=0)),
                ('num_thread_observado', models.IntegerField(blank=True, null=True)),
                ('visto_pela_ultima_vez', models.DateTimeField(blank=True, null=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_ollama', to='cluster.maquina')),
            ],
            options={
                'db_table': 'cluster_maquina_modelo_ollama',
            },
        ),
        migrations.AddConstraint(
            model_name='maquinamodeloollama',
            constraint=models.UniqueConstraint(fields=('maquina', 'nome_modelo'), name='uniq_maquina_modelo_ollama'),
        ),
    ]
