# Generated by Django 5.0.6 on 2026-09-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_maquina_ollama_endpoint_maquinamodeloollama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinamodeloollama',
            name='num_ctx_observado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
