# Generated by Django 5.0.6 on 2026-09-17 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cluster', '0003_maquinamodeloollama_num_ctx_observado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='maquina',
            constraint=models.UniqueConstraint(fields=('organizacao', 'apelido'), name='uniq_maquina_organizacao_apelido'),
        ),
    ]
