# Generated by Django 5.0.6 on 2026-09-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0004_maquina_uniq_maquina_organizacao_apelido'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='hospeda_infra_compartilhada',
            field=models.BooleanField(default=False),
        ),
    ]
