# Generated by Django 5.0.6 on 2026-10-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0005_maquina_hospeda_infra_compartilhada'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='gateway_endpoint',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
