# Generated by Django 5.0.6 on 2026-10-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0006_maquina_gateway_endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='hospeda_infra_compartilhada',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='modo',
        ),
    ]
