# Generated by Django 5.0.6 on 2026-10-04 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0007_remove_modo_hospeda_infra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='token_hash',
        ),
        migrations.DeleteModel(
            name='EventoReplicacao',
        ),
    ]
