# Generated by Django 5.0.6 on 2026-10-04 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cluster', '0008_remove_replicacao_e_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='capacidades_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='maquina',
            name='conferida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maquina',
            name='did',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='eh_local',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maquina',
            name='endpoint_controle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='maquina',
            name='estado',
            field=models.CharField(choices=[('pendente', 'Pendente de conferência'), ('confirmado', 'Confirmado'), ('revogado', 'Revogado')], default='pendente', max_length=12),
        ),
        migrations.AddField(
            model_name='maquina',
            name='impressao_digital_conferida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='tipo',
            field=models.CharField(choices=[('proprio', 'Próprio (mesmo dono)'), ('terceiro', 'Terceiro')], default='terceiro', max_length=10),
        ),
        migrations.AddField(
            model_name='maquina',
            name='ultimo_pull_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='ultimo_pull_erro',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='maquina',
            constraint=models.UniqueConstraint(condition=models.Q(('did__isnull', False)), fields=('organizacao', 'did'), name='uniq_maquina_organizacao_did'),
        ),
        migrations.AddConstraint(
            model_name='maquina',
            constraint=models.UniqueConstraint(condition=models.Q(('eh_local', True)), fields=('organizacao',), name='uniq_maquina_local_por_organizacao'),
        ),
    ]
