# Generated by Django 5.0.6 on 2026-10-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0010_convite_enrolamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='pull_falhas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maquina',
            name='ultima_tentativa_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquinamodeloollama',
            name='carregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maquinamodeloollama',
            name='digest',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='maquinamodeloollama',
            name='familia',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='maquinamodeloollama',
            name='parametros',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='maquinamodeloollama',
            name='quantizacao',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='maquinamodeloollama',
            name='tamanho_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquinastatus',
            name='disco_ollama_livre_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquinastatus',
            name='ollama_disponivel',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquinastatus',
            name='ollama_versao',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
