# Generated by Django 5.0.6 on 2026-10-04 22:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0011_inventario_ollama_e_pull'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacaoModeloOllama',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('pull', 'Instalar'), ('delete', 'Remover')], max_length=10)),
                ('modelo', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('executando', 'Executando'), ('concluida', 'Concluída'), ('falhou', 'Falhou'), ('cancelada', 'Cancelada')], default='pendente', max_length=12)),
                ('bytes_total', models.BigIntegerField(blank=True, null=True)),
                ('bytes_concluidos', models.BigIntegerField(default=0)),
                ('fase', models.CharField(blank=True, max_length=120)),
                ('erro', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=155)),
                ('ator_afirmado', models.JSONField(blank=True, default=dict)),
                ('operacao_remota_id', models.UUIDField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_progresso_em', models.DateTimeField(blank=True, null=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes_modelo', to='cluster.maquina')),
                ('origem_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cluster.maquina')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cluster_operacao_modelo_ollama',
                'ordering': ['-criada_em'],
                'indexes': [models.Index(fields=['maquina', '-criada_em'], name='cluster_ope_maquina_a13935_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='operacaomodeloollama',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pendente', 'executando'])), fields=('maquina', 'modelo'), name='uma_operacao_ativa_por_maquina_modelo'),
        ),
    ]
