# Generated by Django 5.0.6 on 2026-09-17 18:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cluster', '0005_maquina_hospeda_infra_compartilhada'),
        ('events', '0002_pipelineevent_avulso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadaLLM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ocorreu_em', models.DateTimeField(db_index=True)),
                ('finalidade', models.CharField(choices=[('classificacao_automatica', 'Classificação automática (page_type)'), ('extracao_automatica', 'Extração automática (schema+dados)'), ('estruturacao_manual', 'Estruturação manual'), ('comparacao_juiz', 'Comparação (juiz)'), ('gateway_externo', 'Gateway OpenAI-compatível')], max_length=30)),
                ('provider', models.CharField(choices=[('anthropic', 'Claude (externo)'), ('ollama', 'Ollama')], max_length=20)),
                ('modelo_solicitado', models.CharField(max_length=255)),
                ('modelo_resposta', models.CharField(blank=True, max_length=255)),
                ('sucesso', models.BooleanField()),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('tokens_entrada', models.IntegerField(blank=True, null=True)),
                ('tokens_saida', models.IntegerField(blank=True, null=True)),
                ('chars_enviados', models.IntegerField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, max_length=40)),
                ('request_id', models.CharField(blank=True, max_length=120)),
                ('num_thread', models.IntegerField(blank=True, null=True)),
                ('num_ctx', models.IntegerField(blank=True, null=True)),
                ('subject_type', models.CharField(blank=True, max_length=40)),
                ('subject_id', models.UUIDField(blank=True, null=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chamada_llm', to='events.pipelineevent')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamadas_llm', to='cluster.maquina')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamadas_llm', to='accounts.organization')),
            ],
            options={
                'db_table': 'events_chamada_llm',
                'indexes': [models.Index(fields=['-ocorreu_em'], name='chamada_llm_ocorreu_em_idx'), models.Index(fields=['maquina', '-ocorreu_em'], name='chamada_llm_maquina_dt_idx'), models.Index(fields=['provider', 'modelo_resposta', '-ocorreu_em'], name='chamada_llm_modelo_dt_idx'), models.Index(fields=['tenant', '-ocorreu_em'], name='chamada_llm_tenant_dt_idx'), models.Index(fields=['subject_type', 'subject_id'], name='chamada_llm_subject_idx')],
            },
        ),
    ]
