# Generated by Django 5.0.6 on 2026-10-04 13:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaveInstancia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('did', models.CharField(max_length=100, unique=True)),
                ('privada_cifrada', models.TextField()),
                ('estado', models.CharField(choices=[('ativa', 'Ativa'), ('aposentada', 'Aposentada'), ('comprometida', 'Comprometida')], default='ativa', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'federacao_chave_instancia',
            },
        ),
        migrations.AddConstraint(
            model_name='chaveinstancia',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ativa')), fields=('estado',), name='uma_chave_ativa_por_instancia'),
        ),
    ]
