# Generated by Django 5.0.6 on 2026-10-04 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('artifacts', '0017_claim_evidence'),
        ('federacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('arquivado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='espacos', to='accounts.organization')),
            ],
            options={
                'db_table': 'federacao_space',
            },
        ),
        migrations.CreateModel(
            name='EspacoArtefato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incluido_em', models.DateTimeField(auto_now_add=True)),
                ('artefato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espaco_itens', to='artifacts.artifact')),
                ('incluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='federacao.space')),
            ],
            options={
                'db_table': 'federacao_espaco_artefato',
            },
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.UniqueConstraint(fields=('organizacao', 'nome'), name='uniq_space_organizacao_nome'),
        ),
        migrations.AddConstraint(
            model_name='espacoartefato',
            constraint=models.UniqueConstraint(fields=('espaco', 'artefato'), name='uniq_espaco_artefato'),
        ),
    ]
