# Generated by Django 5.0.6 on 2026-10-04 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('federacao', '0002_space'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraReplicacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('efeito', models.CharField(choices=[('permitir', 'Permitir'), ('negar', 'Negar')], max_length=10)),
                ('sentido', models.CharField(choices=[('enviar', 'Ao enviar'), ('receber', 'Ao receber')], max_length=10)),
                ('par_ref', models.CharField(blank=True, help_text='Nome ou chave do par; vazio = qualquer.', max_length=200, null=True)),
                ('par_tipo', models.CharField(blank=True, choices=[('proprio', 'Próprio (mesmo dono)'), ('terceiro', 'Terceiro')], max_length=10, null=True)),
                ('nivel', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_objeto', models.CharField(blank=True, max_length=30, null=True)),
                ('espaco_urn', models.CharField(blank=True, max_length=60, null=True)),
                ('objeto_urn', models.CharField(blank=True, max_length=60, null=True)),
                ('valida_ate', models.DateTimeField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('revogada_em', models.DateTimeField(blank=True, null=True)),
                ('padrao', models.BooleanField(default=False)),
                ('chave_padrao', models.CharField(blank=True, max_length=60, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_replicacao', to='accounts.organization')),
            ],
            options={
                'db_table': 'federacao_regra_replicacao',
            },
        ),
        migrations.AddConstraint(
            model_name='regrareplicacao',
            constraint=models.UniqueConstraint(condition=models.Q(('chave_padrao__isnull', False)), fields=('organizacao', 'chave_padrao'), name='uniq_regra_replicacao_padrao'),
        ),
        migrations.AddConstraint(
            model_name='regrareplicacao',
            constraint=models.CheckConstraint(check=models.Q(('objeto_urn__isnull', True), ('valida_ate__isnull', False), _connector='OR'), name='regra_com_objeto_exige_validade'),
        ),
    ]
