# Generated by Django 5.0.6 on 2026-10-11 03:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cluster', '0012_operacao_modelo_ollama'),
        ('federacao', '0003_regra_replicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoFederado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direcao', models.CharField(choices=[('emitido', 'Emitido'), ('recebido', 'Recebido')], max_length=10)),
                ('evento_id', models.CharField(help_text='`sha256:…` do envelope sem a assinatura.', max_length=80)),
                ('tipo', models.CharField(max_length=60)),
                ('espaco_urn', models.CharField(max_length=60)),
                ('autor_did', models.CharField(max_length=100)),
                ('prev', models.CharField(blank=True, max_length=80, null=True)),
                ('objeto_urn', models.CharField(blank=True, max_length=60, null=True)),
                ('envelope_bruto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_federados', to='accounts.organization')),
                ('par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cluster.maquina')),
            ],
            options={
                'db_table': 'federacao_evento',
                'indexes': [models.Index(fields=['organizacao', 'direcao', 'autor_did', 'espaco_urn', 'criado_em'], name='federacao_e_organiz_ef4481_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='eventofederado',
            constraint=models.UniqueConstraint(fields=('organizacao', 'direcao', 'evento_id'), name='uniq_evento_federado'),
        ),
    ]
