# Generated by Django 5.0.6 on 2026-05-10 01:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('registry_url', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password_encrypted', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_registries', to='accounts.organization')),
            ],
            options={
                'db_table': 'infrastructure_image_registry',
            },
        ),
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('provider_type', models.CharField(choices=[('external', 'Externo'), ('local', 'Local')], max_length=20)),
                ('endpoint_url', models.URLField(blank=True, null=True)),
                ('api_key_encrypted', models.CharField(blank=True, max_length=255, null=True)),
                ('model_name', models.CharField(max_length=255)),
                ('allowed_classifications', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_providers', to='accounts.organization')),
            ],
            options={
                'db_table': 'infrastructure_llm_provider',
            },
        ),
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('endpoint_url', models.URLField()),
                ('auth_token_encrypted', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('health_status', models.CharField(choices=[('ok', 'OK'), ('degraded', 'Degradado'), ('unavailable', 'Indisponível'), ('unknown', 'Desconhecido')], default='unknown', max_length=20)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_servers', to='accounts.organization')),
            ],
            options={
                'db_table': 'infrastructure_mcp_server',
            },
        ),
        migrations.CreateModel(
            name='ContainerImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=100)),
                ('image_type', models.CharField(choices=[('agent', 'Agente'), ('tool', 'Ferramenta'), ('worker', 'Worker')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('pull_status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Falhou'), ('unknown', 'Desconhecido')], default='unknown', max_length=20)),
                ('last_pull_attempt', models.DateTimeField(blank=True, null=True)),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='infrastructure.imageregistry')),
            ],
            options={
                'db_table': 'infrastructure_container_image',
                'unique_together': {('registry', 'image_name', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='MCPTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('input_schema', models.JSONField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='infrastructure.mcpserver')),
            ],
            options={
                'db_table': 'infrastructure_mcp_tool',
                'unique_together': {('server', 'tool_name')},
            },
        ),
    ]
