# Generated by Django 5.0.6 on 2026-10-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='vendor',
            field=models.CharField(choices=[('anthropic', 'Anthropic (Claude)')], default='anthropic', max_length=20),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='api_key_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
