# Generated by Django 5.0.6 on 2026-05-10 01:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('pessoa', 'Pessoa Física'), ('empresa', 'Pessoa Jurídica'), ('documento', 'Documento'), ('processo', 'Processo'), ('endereco', 'Endereço'), ('evento', 'Evento')], max_length=20)),
                ('content', models.JSONField()),
                ('classification_level', models.CharField(choices=[('publico', 'Público'), ('interno', 'Interno'), ('restrito', 'Restrito'), ('confidencial', 'Confidencial')], default='restrito', max_length=20)),
                ('allow_external_llm', models.BooleanField(default=False)),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('info_type', models.CharField(choices=[('fato', 'Fato'), ('opiniao', 'Opinião'), ('inferencia', 'Inferência')], max_length=20)),
                ('sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classified_artifacts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='accounts.organization')),
            ],
            options={
                'db_table': 'artifacts_artifact',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('artifact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='artifacts.artifact')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'permissions': [('add_auditlog', 'Can add audit log')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('usuario', 'Usuário'), ('organizacao', 'Organização')], max_length=20)),
                ('recipient_id', models.UUIDField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('expirado', 'Expirado'), ('revogado', 'Revogado')], default='ativo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharings', to='artifacts.artifact')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_sharings', to=settings.AUTH_USER_MODEL)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_sharings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'artifacts_sharing',
            },
        ),
    ]
