# Generated by Django 5.0.6 on 2026-09-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0008_documenttext_dom_representation'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttext',
            name='dados_estruturados_dom2parser',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documenttext',
            name='dados_estruturados_extruct',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
