# Generated by Django 5.0.6 on 2026-09-15 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('artifacts', '0009_documenttext_dados_estruturados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencias', models.JSONField(default=list)),
                ('modelo_juiz_provider', models.CharField(choices=[('anthropic', 'Claude (externo)'), ('ollama', 'Ollama (local)')], max_length=20)),
                ('modelo_juiz_model_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('executando', 'Executando'), ('concluido', 'Concluído'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=155)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'artifacts_comparacao',
            },
        ),
        migrations.CreateModel(
            name='EstruturacaoLLM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('anthropic', 'Claude (externo)'), ('ollama', 'Ollama (local)')], max_length=20)),
                ('model_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('executando', 'Executando'), ('concluido', 'Concluído'), ('vazio', 'Vazio'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=500)),
                ('structured_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=155)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'artifacts_estruturacao_llm',
            },
        ),
        migrations.RemoveConstraint(
            model_name='urlpatterncache',
            name='unique_tenant_domain_path',
        ),
        migrations.RenameIndex(
            model_name='urlpatterncache',
            new_name='artifacts_u_tenant__990bc1_idx',
            old_name='artifacts_url_tenant_domain_idx',
        ),
        migrations.AddField(
            model_name='comparacao',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparacoes', to='artifacts.artifact'),
        ),
        migrations.AddField(
            model_name='comparacao',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparacoes', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='comparacao',
            name='triggered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estruturacaollm',
            name='document_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estruturacoes_llm', to='artifacts.documenttext'),
        ),
        migrations.AddField(
            model_name='estruturacaollm',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estruturacoes_llm', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='estruturacaollm',
            name='triggered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estruturacoes_llm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comparacao',
            index=models.Index(fields=['artifact', '-created_at'], name='artifacts_c_artifac_f87ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='estruturacaollm',
            index=models.Index(fields=['document_text', '-created_at'], name='artifacts_e_documen_4c6303_idx'),
        ),
    ]
