# Generated by Django 5.0.6 on 2026-09-17 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0010_comparacao_estruturacaollm_and_more'),
        ('cluster', '0005_maquina_hospeda_infra_compartilhada'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparacao',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparacoes', to='cluster.maquina'),
        ),
        migrations.AddField(
            model_name='estruturacaollm',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estruturacoes_llm', to='cluster.maquina'),
        ),
    ]
