# Generated by Django 5.0.6 on 2026-09-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0013_documenttext_tamanhos'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttext',
            name='dados_estruturados_deterministico',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
