# Generated by Django 5.0.6 on 2026-10-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0014_documenttext_dados_estruturados_deterministico'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='blob_hash',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
