# Generated by Django 5.0.6 on 2026-10-04 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('artifacts', '0015_artifact_blob_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraClassificacaoDominio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dominio', models.CharField(help_text='Ex.: bancodobrasil.com.br (cobre www., login. etc.)', max_length=253)),
                ('nivel', models.CharField(choices=[('publico', 'Público'), ('interno', 'Interno'), ('restrito', 'Restrito'), ('confidencial', 'Confidencial')], max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_classificacao_dominio', to='accounts.organization')),
            ],
            options={
                'db_table': 'artifacts_regra_classificacao_dominio',
            },
        ),
        migrations.AddConstraint(
            model_name='regraclassificacaodominio',
            constraint=models.UniqueConstraint(fields=('tenant', 'dominio'), name='uniq_regra_classificacao_tenant_dominio'),
        ),
    ]
