# Generated by Django 5.0.6 on 2026-10-04 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('artifacts', '0016_regra_classificacao_dominio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sujeito_ref', models.CharField(db_index=True, max_length=500)),
                ('predicado', models.CharField(db_index=True, max_length=100)),
                ('objeto_ref', models.CharField(blank=True, max_length=500, null=True)),
                ('objeto_literal', models.TextField(blank=True, null=True)),
                ('autor_ref', models.CharField(max_length=500)),
                ('produtor', models.CharField(max_length=100)),
                ('produtor_versao', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=255)),
                ('extractor_confidence', models.FloatField(blank=True, null=True)),
                ('classification_level', models.CharField(choices=[('publico', 'Público'), ('interno', 'Interno'), ('restrito', 'Restrito'), ('confidencial', 'Confidencial')], max_length=20)),
                ('estado', models.CharField(choices=[('ativa', 'Ativa'), ('retratada', 'Retratada')], default='ativa', max_length=20)),
                ('retratada_em', models.DateTimeField(blank=True, null=True)),
                ('chave', models.CharField(max_length=64)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('artefato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alegacoes', to='artifacts.artifact')),
                ('revisa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisoes', to='artifacts.claim')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alegacoes', to='accounts.organization')),
            ],
            options={
                'db_table': 'artifacts_claim',
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blob_hash', models.CharField(db_index=True, max_length=100)),
                ('localizador_tipo', models.CharField(max_length=50)),
                ('localizador', models.JSONField(default=dict)),
                ('trecho', models.CharField(blank=True, max_length=500)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='artifacts.claim')),
            ],
            options={
                'db_table': 'artifacts_evidence',
            },
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(fields=('artefato', 'chave'), name='uniq_claim_artefato_chave'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('objeto_literal__isnull', True), ('objeto_ref__isnull', False)), models.Q(('objeto_literal__isnull', False), ('objeto_ref__isnull', True)), _connector='OR'), name='claim_objeto_ref_xor_literal'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(check=models.Q(('extractor_confidence__isnull', True), models.Q(('extractor_confidence__gte', 0), ('extractor_confidence__lte', 1)), _connector='OR'), name='claim_confianca_entre_0_e_1'),
        ),
    ]
